# Generated by Django 4.2.13 on 2024-06-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
                ('date', models.DateField()),
                ('In_time', models.TimeField()),
                ('Out_time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
