# Generated by Django 4.2.13 on 2024-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('studentid', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=100)),
                ('Dept', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
